Feature/create location
caelum-airlines/clines-api pull request #9
Opened 2020-04-29 12:38 UTC by alexandreMelloTW

:warning: _Is there something everyone needs to know before merging?_ (Optional)

### Requirement 
<details>
    <summary>
        <strong>Clearly explain your requirement.</strong> 
    </summary>
    <p>
       Implement an endpoint to create a Location.
    </p>
</details>

### Solution
<details>
    <summary>
        <strong>Clearly explain your solution.</strong>           
    </summary>
    <p>
1. Created `Location Controller` to receive an `Location Form` and send it to `Location Service`

2. Created `Location Service` to _map_ `Location Form` into `Location` and save it by `Location Repository`.

3. Created `Location Repository` to handle _database persistence_.
    </p>
</details>

### How to test
<details>
    <summary>
        <strong>Request for test.</strong>
    </summary>
    <p>
curl -v -X POST http://localhost:8080/location -H 'Content-Type: application/json' -d '{ "country": "Brazil", "state": "SP", "city": "São Paulo" }'
   </p>
</details>

2020-04-29 19:06 UTC, MarceloLeite2604 approved these changes

2020-04-30 03:33 UTC, fwfurtado commented on pom.xml
> +            <artifactId>spring-cloud-contract-shade</artifactId>
We need of this dependency?

2020-04-30 03:46 UTC, fwfurtado requested changes

2020-04-30 03:46 UTC, fwfurtado commented on src/main/java/br/com/caelum/clines/shared/domain/Country.java
> +        for (Country value : values()) {
What do you think about to use: 
```java
EnumSet.allOf(Country.class)
.stream()
.filter(countryDescription -> countryDescription.equals(description))
.findFirst()
.orElseThrow(() -> new IllegalArgumentException("Country " + description + " not found."));
```

2020-04-30 12:50 UTC, alexandreMelloTW commented on src/main/java/br/com/caelum/clines/shared/domain/Country.java
> +        for (Country value : values()) {
resolvido

2020-04-30 12:50 UTC, alexandreMelloTW commented on pom.xml
> +            <artifactId>spring-cloud-contract-shade</artifactId>
removed

2020-04-30 12:58 UTC, fwfurtado approved these changes

2020-04-30 13:01 UTC, merged